### ISSUE TITLE
If i use allowNumbersOnly and isPasswordInput numeric keyboard not work

### ISSUE THREAD

**Issue by morant901** [code-farmz/ng-otp-input#46]
Hello, I try to implement a input with the properties allowNumbersOnly and isPasswordInput but i want that the keyboard on mobile was numeric.

**Comment by morant901** [comment]
@code-farmz please help me

**Comment by code-farmz** [comment]
since input type password is used in case off `isPasswordInput ` number keyboard might not be working. You can escape isPasswordInput and use ` -webkit-text-security: disc;` [Please read this MSDN using before using this](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security)

Set style class on the input using inputClass attribute like:-



and in sytle.css set
